<h1>Update Checker Page</h1>

<?php
if($new_version_available){
	?>
	<h3> A new Eve version is available !</h3>
	<p>An update is strongly recommended !</p>
	<?php
}elseif($new_prices_available){
	?>
	<h3>Days without update : <?php echo $days_without_update->format('%a'); ?> (last time was on <?php echo $last_update->format("d-m-Y"); ?>)</h3>
	<p>Would you like to update ?</p>
	<?php
}else{
	?>
	<h3>Last update is less than a day ago</h3>
	<p>Would you like to update anyway ?</p>
	<?php
}
?>
<a href="<?php echo $update_link; ?>">
    <button>UPDATE</button>
</a>